# Language Classification with Naive Bayes in Python

## Problem Statement



In [101]:
import matplotlib
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
import matplotlib.pyplot as plt
plt.style.use('ggplot')

import numpy as np
import string

from collections import defaultdict

from sklearn.metrics import f1_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

import joblib
import pickle as pkl
# from yellowbrick.classifier import ConfusionMatrix

<a id='intro'></a>
# Introduction

<a id='task1'></a>
# Task 1: Data Exploration and Visualization

In [49]:
def open_file(filename):
    with open(filename, 'r',encoding="utf8") as f:
        data = f.readlines()
    return data

In [50]:
data_raw = dict()
data_raw['sk'] =  open_file('Data/Sentences/train_sentences.sk')
data_raw['cs'] =  open_file('Data/Sentences/train_sentences.cs')
data_raw['en'] =  open_file('Data/Sentences/train_sentences.en')

In [51]:
data_raw['en']

['I can understand your approach a little bit.\n',
 'Membership of Parliament: see Minutes\n',
 'The establishment of a joint EU resettlement programme (\n',
 'Decentralisation is very important for sustainable energy.\n',
 'A majority rejected these solutions and wishes to stay in Bosnia.\n',
 '(RO) At the start of the year, the unemployment rate reached 10%, while the deficit has grown in numerous Member States.\n',
 'We are, as honourable Members know, supporting projects worldwide in the fight against racism, xenophobia or discrimination on any ground.\n',
 'Agenda for next sitting: see Minutes\n',
 'In addition, communities should be supported both financially and by specific solutions on the regional level, in order to improve the level of communal services.\n',
 'This includes all commercial aspects of exploitation as well as the legal, contractual and financing structures of the different exploitation models that will ensure that a stable governance model is put into place.\n',

In [52]:
def show_statistics(data):
    for language, sentences in data.items():
        
        word_list = ' '.join(sentences).split()
        
        number_of_sentences = len(sentences)
        number_of_words = len(word_list)
        number_of_unique_words = len(set(word_list))
        sample_extract = ''.join(sentences[0].split(' ')[:7])
    
        print(f'Language: {language}')
        print('-----------------------')
        print(f'Number of sentences\t:\t {number_of_sentences}')
        print(f'Number of words\t\t:\t {number_of_words}')
        print(f'Number of unique words\t:\t {number_of_unique_words}')
        print(f'Sample extract\t\t:\t {sample_extract}...\n')

In [53]:
show_statistics(data_raw)

Language: sk
-----------------------
Number of sentences	:	 100
Number of words		:	 2016
Number of unique words	:	 1322
Sample extract		:	 PándeGrandesPascualjasnevysvetlil,aká...

Language: cs
-----------------------
Number of sentences	:	 10
Number of words		:	 158
Number of unique words	:	 141
Sample extract		:	 Upozorňujeme,žejejímcílemješetřitpenězi...

Language: en
-----------------------
Number of sentences	:	 100
Number of words		:	 2381
Number of unique words	:	 1037
Sample extract		:	 Icanunderstandyourapproachalittle...



<a id='task2'></a>
# Task 2: Data Cleaning and Preprocessing

In [54]:
def text_process(text):
    
    preprocessed_text = text
    preprocessed_text = text.lower().replace('-',' ')
    translation_table = str.maketrans('\n',' ', string.punctuation+string.digits)
    preprocessed_text = preprocessed_text.translate(translation_table)
    
    return preprocessed_text

In [55]:
data_preprocessed = {k: [text_process(sentence) for sentence in v] for k, v in data_raw.items()}

In [56]:
print('ORIGINAL STATISTICS')
show_statistics(data_raw)
print('PREPROCESSED STATISTICS :')
show_statistics(data_preprocessed)

ORIGINAL STATISTICS
Language: sk
-----------------------
Number of sentences	:	 100
Number of words		:	 2016
Number of unique words	:	 1322
Sample extract		:	 PándeGrandesPascualjasnevysvetlil,aká...

Language: cs
-----------------------
Number of sentences	:	 10
Number of words		:	 158
Number of unique words	:	 141
Sample extract		:	 Upozorňujeme,žejejímcílemješetřitpenězi...

Language: en
-----------------------
Number of sentences	:	 100
Number of words		:	 2381
Number of unique words	:	 1037
Sample extract		:	 Icanunderstandyourapproachalittle...

PREPROCESSED STATISTICS :
Language: sk
-----------------------
Number of sentences	:	 100
Number of words		:	 1996
Number of unique words	:	 1207
Sample extract		:	 pándegrandespascualjasnevysvetlilaká...

Language: cs
-----------------------
Number of sentences	:	 10
Number of words		:	 155
Number of unique words	:	 133
Sample extract		:	 upozorňujemežejejímcílemješetřitpenězi...

Language: en
-----------------------
Number of sentences	

<a id='task3'></a>
# Task 3: The Naive Bayes Model

**Bayes' Theorem**

\begin{equation}
P(A | B)=\frac{P(B | A) \times P(A)}{P(B)}
\end{equation}

Now, let's translate this theory into our specific problem. In our case, where we want to categorise a sentence `my name is Sudarshan` into one of `sk`, `cs`, or `en`, the following are the probabilities we want to determine.

\begin{equation}
P(\text {sk} | \text {my name is Sudarshan})=\frac{P(\text {my name is Sudarshan} | \text {sk}) \times P(\text {sk})}{P(\text {my name is Sudarshan})}
\end{equation}

\begin{equation}
P(\text {cs} | \text {my name is Sudarshan})=\frac{P(\text {my name is Sudarshan} | \text {cs}) \times P(\text {cs})}{P(\text {my name is Sudarshan})}
\end{equation}

\begin{equation}
P(\text {en} | \text {my name is Sudarshan})=\frac{P(\text {my name is Sudarshan} | \text {en}) \times P(\text {en})}{P(\text {my name is Sudarshan})}
\end{equation}

## Unseen Data

Since we assume conditional independence across our features, our numerator term for any of the above equations can be broken into the following.

\begin{equation}
P(\text {my name is Sudarshan} | \text {en}) = P(\text {my} | \text {en}) \times P(\text {name} | \text {en}) \times P(\text {is} | \text {en}) \times P(\text {Sudarshan} | \text {en})
\end{equation}

## Vectorizing Training Data

|Sentence   	||   my   	| is 	| I 	| love 	| name 	| it 	| Sudarshan 	|
|-----------------	||:------:	|:--:	|:-:	|:----:	|:----:	|:--------:	|:---:	|
| my name is Sudarshan  	||    1   	|  1 	| 0 	|   0  	|   1  	|     0    	|  1  	|
| I love it 	||    0   	|  0 	| 1 	|   1  	|   0  	|     1    	|  0  	|

In [57]:
sentences_train, y_train =[], []
for k, v in data_preprocessed.items():
    for sentence in v:
        sentences_train.append(sentence)
        y_train.append(k)
        

In [58]:
vectorizer = CountVectorizer()

In [59]:
x_train = vectorizer.fit_transform(sentences_train)
x_train

<210x2208 sparse matrix of type '<class 'numpy.int64'>'
	with 3867 stored elements in Compressed Sparse Row format>

## Initializing Model Parameters and Training

In [60]:
naive_bayes = MultinomialNB()
naive_bayes.fit(x_train,y_train) #alpha is smoothening constant, takes into account unseen literals like name - 'Sudarshan'

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

## Vectorizing Validation Data and Evaluating Model

In [61]:
data_val = dict()
data_val['sk'] = open_file('Data/Sentences/val_sentences.sk')
data_val['cs'] = open_file('Data/Sentences/val_sentences.cs')
data_val['en'] = open_file('Data/Sentences/val_sentences.en')

data_val_preprocessed = {k: [text_process(sentence) for sentence in v] for k,v in data_val.items()}

In [62]:
sentences_val, y_val = [], []
for k,v in data_val_preprocessed.items():
    for sentence in v:
        sentences_val.append(sentence)
        y_val.append(k)

In [63]:
x_val = vectorizer.transform(sentences_val)

In [64]:
predictions = naive_bayes.predict(x_val)
predictions

array(['sk', 'sk', 'sk', ..., 'en', 'en', 'en'], dtype='<U2')

In [65]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_val, predictions, labels=['sk','cs','en']))

[[4886    0  114]
 [4077  534  389]
 [   0    0 5000]]


In [66]:
f1_score(y_val, predictions, average='weighted')

0.6149824401040264

<a id='task4'></a>
# Task 4: Simple Adjustments and Highlighting Model Shortcomings

In [67]:
naive_bayes = MultinomialNB(alpha= 0.0001, fit_prior = False) 
#alpha takes care for values which are not present in language dictionary.
# fit_prior is false to avoid prior probability otherwise prob will be biased towards 'sk' and 'eng'.Since cs has less sentences.
naive_bayes.fit(x_train,y_train)
predictions = naive_bayes.predict(x_val)
confusion_matrix(y_val,predictions, ['sk','cs','en'])

array([[4839,  155,    6],
       [2080, 2865,   55],
       [   0,   52, 4948]], dtype=int64)

In [68]:
f1_score(y_val, predictions, average='weighted')

0.8368507601649364

<a id='task5'></a>
# Task 5: Using Subwords to Shift Perspective

**Dummy Dataset**

playing ; eating ; play ; reads ; tea

**Step 1**

Break each word into characters

playing > p l a y i n g


**Step 2**

Find common character sequences

ea, ing, play

**Step 3**

Convert dataset using these subwords into

play ing ; ea t ing ; play ; r ea d s ; t ea

## get_vocab Function :
1. Takes in sentence_train as input and splits each sentence into words.
2. Followed by splitting each word into letters and storing them in a dict with their frequency.


## get_stats Function :
1. Takes in vocab dictionary as input.
2. Split each word into letters and store it in symbols.
3. Form a dictionary with keys as two frequent letters and values with their frequency.
4. Return the pair frequency.


In [69]:
# taken from https://arxiv.org/abs/1508.07909

import re, collections
def get_stats(vocab):
    pairs = collections.defaultdict(int) 
    for word, freq in vocab.items():
        symbols = word.split()
        for i in range(len(symbols)-1):
            pairs[symbols[i],symbols[i+1]] += freq 
    return pairs

def merge_vocab(pair, v_in):
    v_out = {}
    bigram = re.escape(' '.join(pair))
    p = re.compile(r'(?<!\S)' + bigram + r'(?!\S)')
    for word in v_in:
        w_out = p.sub(''.join(pair), word)
        v_out[w_out] = v_in[word] 
    return v_out

In [70]:
def get_vocab(data):

    words = []
    for sentence in data:
        words.extend(sentence.split())
     
    vocab = defaultdict(int)
    for word in words:
        vocab[' '.join(word)] += 1
        
    return vocab

In [71]:
vocab = get_vocab(sentences_train)
# vocab

In [72]:
# also taken from original paper
for i in range(100):
    pairs = get_stats(vocab)
#     print(pairs)
    best = max(pairs, key=pairs.get)
#     print(best)
    vocab = merge_vocab(best, vocab)
     

In [73]:
merges = defaultdict(int)
for k, v in vocab.items():
    for subword in k.split():
        if len(subword) >=2:
            merges[subword] += v

In [74]:
merge_ordered = sorted(merges, key=merges.get, reverse=True)

In [75]:
pkl.dump(merge_ordered, open('Data/Auxiliary/merge_ordered.pkl', 'wb'))

In [76]:
def split_into_subwords(text):
    merges = pkl.load(open('Data/Auxiliary/merge_ordered.pkl', 'rb'))
    subwords = []
    for word in text.split():
        for subword in merges:
            subword_count = word.count(subword)
            if subword_count > 0:
                word = word.replace(subword, ' ')
                subwords.extend([subword]*subword_count)
    return ' '.join(subwords)4

In [77]:
split_into_subwords('Hello My name is Sudarshan')

'lo na me is an ar'

In [78]:
data_preprocessed_subwords = {k: [split_into_subwords(sentence) for sentence in v] for k,v in data_preprocessed.items()}

In [79]:
show_statistics(data_preprocessed_subwords)

Language: sk
-----------------------
Number of sentences	:	 100
Number of words		:	 3431
Number of unique words	:	 75
Sample extract		:	 deandealasneas...

Language: cs
-----------------------
Number of sentences	:	 10
Number of words		:	 239
Number of unique words	:	 59
Sample extract		:	 pojemeoržejele...

Language: en
-----------------------
Number of sentences	:	 100
Number of words		:	 3863
Number of unique words	:	 75
Sample extract		:	 anstanerouroch...



In [80]:
data_train_subwords = []
for sentence in sentences_train:
    data_train_subwords.append(split_into_subwords(sentence))

In [81]:
data_val_subwords = []
for sentence in sentences_val:
    data_val_subwords.append(split_into_subwords(sentence))


In [82]:
vectorizer = CountVectorizer()

In [83]:
x_train = vectorizer.fit_transform(data_train_subwords)
x_val = vectorizer.transform(data_val_subwords)

In [84]:
naive_bayes = MultinomialNB(alpha= 1.0, fit_prior = False)

In [85]:
naive_bayes.fit(x_train,y_train)
predictions = naive_bayes.predict(x_val)

In [91]:
confusion_matrix(y_val,predictions,labels=['sk','cs','en'])

array([[4684,  303,   13],
       [1799, 3134,   67],
       [  14,   61, 4925]], dtype=int64)

In [87]:
f1_score(y_val ,predictions, average='weighted')

0.8456381060126386

In [88]:
joblib.dump(naive_bayes, 'Data/Models/final_model.joblib')
joblib.dump(vectorizer, 'Data/Vectorizers/final_model.joblib')

['Data/Vectorizers/final_model.joblib']

### EVALUATING OUR LANGUAGE CLASSIFICATION MODEL

In [89]:
model = joblib.load('Data/Models/final_model.joblib')
vectorizer = joblib.load('Data/Vectorizers/final_model.joblib')

In [104]:
text = "czec a slovenština jsou velmi podobné jazyky." #czec and slovak are very similar languages.
text = text_process(text)
text = [split_into_subwords(text)]
text_vectorized = vectorizer.transform(text)

model.predict(text_vectorized)[0]

'cs'